language: elixir
elixir:
  - 1.3
otp_release:
  - 18.1
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration
